### ISSUE TITLE
Fuzzy completion matching

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus-community/promql-langserver#128]
## Proposal

Completions are currently filtered using `strings.HasPrefix`.

However it would be nice to replace this by a fuzzy matching algorithm.

### Example

* User types `request`
* Language server should include metrics like `http_requests_total` in the offered completions.

**Comment by drumilpatel2000** [comment]
@slrtbtfs Can I work on this?

**Comment by slrtbtfs** [comment]
Sure.

**Comment by slrtbtfs** [comment]
(I kinda hoped for that when creating the issue.)

**Comment by drumilpatel2000** [comment]
How about [this](https://github.com/schollz/closestmatch) library?

**Comment by drumilpatel2000** [comment]
My bad, Probably should build a function

**Comment by slrtbtfs** [comment]
Hmmm. That lib has a chrash bug open for years that didn't even get a reaction: https://github.com/schollz/closestmatch/issues/9

> My bad, Probably should build a function

Usually using a good lib works better than coming up with your own approach, especially for complex algorithms and well studied problems.

How about https://github.com/sahilm/fuzzy ?

**Comment by drumilpatel2000** [comment]
Should we add prioritization? 
Like `request_drumil` will come first then `tobias_request`

**Comment by slrtbtfs** [comment]
> Should we add prioritization?

Yes.

The `SortText` field in the completions can be used for that. It's already used to prioritize functions over metric names.

**Comment by slrtbtfs** [comment]
@drumilpatel2000 Are you still planning to work on this?

**Comment by haibeey** [comment]
@slrtbtfs i would like to work on this if it's okay?

**Comment by slrtbtfs** [comment]
@haibeey That would be great!

**Comment by haibeey** [comment]
okay i would work out something ASAP

**Comment by slrtbtfs** [comment]
PR #156 introduced fuzzy completion matching for metric names.

Implementing it for the other completion types still needs to happen but should be fairly straightforward. 

Do you want to do that as well @haibeey ?

**Comment by haibeey** [comment]
yes! i would have a look. any pointers to other completion types would be appreciated

**Comment by Nexucis** [comment]
PR #158 closed this issue
