### ISSUE TITLE
Change copyright to "prometheus authors" or some inclusive group

### ISSUE THREAD

**Issue by squat** [prometheus-community/promql-langserver#138]
Now that this project is in the prometheus-community org, I think that it would be good for the community to own the project and for the copyright to change from @slrtbtfs to e.g. `The Prometheus Authors`.

WDYT @slrtbtfs?

**Comment by slrtbtfs** [comment]
What would be the exact legal implications of this?

Since this project contains code from multiple contributors, would they have to agree for changing the copyright notice of existing files?
