### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus-community/promql-langserver#139]
Given @roidelapluie 's [effort](https://github.com/roidelapluie/prometheus/tree/rust) to rewrite Prometheus in Rust, I think we should follow that path and rewrite the language server, too. /s

**Comment by drumilpatel2000** [comment]
Agreed :fireworks: .

**Comment by haibeey** [comment]
what will happen to this repository?

**Comment by roidelapluie** [comment]
This was an April's fool joke :)
