### ISSUE TITLE
Propose the promql-langserver in a Docker container

### ISSUE THREAD

**Issue by Nexucis** [prometheus-community/promql-langserver#146]
Maybe it will be nice to have the langserver in docker. It's usually a nice a way to try it easily

**Comment by slrtbtfs** [comment]
It's not really easier than downloading and running a binary, but I don't have any objections against providing docker images. So if you want to write a Dockerfile and add a CI job to build it, go ahead.

I guess there's a good chance that these images can be pushed to https://hub.docker.com/u/prom/, but we'd have to talk to someone who has access there.

**Comment by Nexucis** [comment]
@SuperQ do you know if it will be possible to push the docker image in https://hub.docker.com/u/prom/ ?
And if yes, then what would be the step to do it (excepting of course the creation of the new job in the CI :))

**Comment by SuperQ** [comment]
Yes, we have a prometheuscommunity Docker org.  We have a bot account that can upload.  We typically use CircleCI.

I can help with the setup.

**Comment by Nexucis** [comment]
Nice ! Thank you :). I'll take a look at the others repo to know how to set up it and let you know when I'll need your help !

**Comment by Nexucis** [comment]
I  take a look at the repository stackdriver_exporter, and it seems the simpler to publish the docker image would be to align the makefile and so to have the common makefile [Makefile](https://github.com/prometheus-community/stackdriver_exporter/blob/master/Makefile.common)

Would you be agree if I'm changing it @slrtbtfs ?

**Comment by slrtbtfs** [comment]
Promu, the build system used by Makefile.common tends to have extremely slow crossbuilds.

I'd prefer if we keep using goreleaser, which has [support for Docker images](https://goreleaser.com/customization/docker/) as well.

**Comment by Nexucis** [comment]
I guess it will depend if it works with prometheus bot mentionned above. I guess it won't be an issue.

@SuperQ is it important to use promu if we want to use the Prometheus bot to publish a docker image ? Or actually it doesn't really matter because we just need to have the bot credentials for docker ?

**Comment by nevill** [comment]
@Nexucis AFAIK, `promu` is used only for building binaries across different platform/arch, like windows/amd64, linux/arm64.

Many prometheus related projects use a shared [Makefile](https://github.com/prometheus/prometheus/blob/master/Makefile.common) to do that.
But, you can definitely choose the way you want to build a docker image.

**Comment by Nexucis** [comment]
thanks for the hint @nevill :)
But I was more questioning if we should follow what other projects are doing (using a common Makefile and then in circle-ci, using a common CI template with predefined job). To be a bit more aligned with others

**Comment by Nexucis** [comment]
issue has been fixed through the PR #159
