### ISSUE TITLE
Make the server robust against bad input

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus-community/promql-langserver#15]
Needed if we want to expose it on a network.

**Comment by metalmatze** [comment]
Might be worth investigating if fuzzing might be a valid solution for tests :)

**Comment by slrtbtfs** [comment]
@metalmatze indeed :)

But first I want to have a look at how the imported gopls code does its error handling.

**Comment by slrtbtfs** [comment]
depends on: #22

**Comment by slrtbtfs** [comment]
The gopls parts have the tendency to (purposely) panic on bad input.

It might make sense to just wrap a `recover()` around each client connection in order to end the connection more or less gracefully in case of any panics.

**Comment by slrtbtfs** [comment]
The current behavior is that the server might panic in case of malformed user input.

This is due to the design of gopls.

If the language server is running inside an IDE with the same permissions of the IDE this shouldn't be overly dramatic.

When the server is providing a connection over websocket these panics are caught, so that only the client providing the malformed input is affected.

This behavior shouldn't be problematic, so I'm closing the issue now.
