### ISSUE TITLE
Weird build failure of prometheus on windows

### ISSUE THREAD

**Issue by Nexucis** [prometheus-community/promql-langserver#160]
On the PR https://github.com/prometheus/prometheus/pull/6872 the build failed for the following reason
```bash
# github.com/prometheus-community/promql-langserver/langserver/cache
vendor\github.com\prometheus-community\promql-langserver\langserver\cache\yaml.go:68:6: undefined: errors.Is
```

**Comment by slrtbtfs** [comment]
Which version of go are you using?

**Comment by Nexucis** [comment]
looking at this recent [commit ](https://github.com/prometheus/prometheus/commit/4424d2c3a494193522ec70c3a7bbf406df6d2952)in Prometheus 

I guess the version used in the build was the version go v1.13

**Comment by slrtbtfs** [comment]
Then the version of github.com/pkg/errors might be to old.

**Comment by Nexucis** [comment]
I rebased the PR and it's fixed. Thanks for the tips @slrtbtfs !

I think you can remove the WIP status of the PR now. I think we are ready for a deep review :)
