### ISSUE TITLE
REST API : promQLExpr in query param can reach the limit of the HTTP URL

### ISSUE THREAD

**Issue by Nexucis** [prometheus-community/promql-langserver#182]
Today all endpoint in the REST API is exposing in a query param the promQL expression:

https://github.com/prometheus-community/promql-langserver/blob/c20ca988ee1fedcda765bc7a4588cbc98415a21d/rest/handler.go#L313

Since a promQL expression can be super huge (basically there is no limit to a promQL expression), there is a risk to reach the limit of the HTTP URL. 

All param should move to a body parameter instead. It will also be the good moment to have a clear data model exposed through the REST API

**Comment by Nexucis** [comment]
And it will certainly be wise to use the HTTP method `POST` instead, to avoid any nasty issue with some old proxy parameter

**Comment by slrtbtfs** [comment]
The Prometheus `api/v1/query` API allows using both  `GET` and `POST` request.

https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries

It probably would be best if we do the same thing.

**Comment by Nexucis** [comment]
I think they did both just for not causing a breaking change. The POST endpoint was added later when the promQL expr reached the limit

**Comment by Nexucis** [comment]
@juliusv in case you are able to breath a bit, could you assess the above statement please ? Thanks by advance for your time :)

**Comment by slrtbtfs** [comment]
Just having a `POST` endpoint would be fine with me as well.

**Comment by Nexucis** [comment]
ok let's do this then
