### ISSUE TITLE
Remove Markdown rendering in the doc

### ISSUE THREAD

**Issue by Nexucis** [prometheus-community/promql-langserver#187]
I don't think it's a good idea that the server is returning a markdown format for the `hover` feature.

The server shouldn't drive the way the json should be displayed.  That's the responsability of the GUI.

For example: 

```json
{
  "contents": {
    "kind": "markdown",
    "value": "## `\u003caggregation\u003e_over_time()`\n\nThe following functions allow aggregating each series of a given range vector\nover time and return an instant vector with per-series aggregation results:\n\n* `avg_over_time(range-vector)`: the average value of all points in the specified interval.\n* `min_over_time(range-vector)`: the minimum value of all points in the specified interval.\n* `max_over_time(range-vector)`: the maximum value of all points in the specified interval.\n* `sum_over_time(range-vector)`: the sum of all values in the specified interval.\n* `count_over_time(range-vector)`: the count of all values in the specified interval.\n* `quantile_over_time(scalar, range-vector)`: the ¤å-quantile (0 Ôëñ ¤å Ôëñ 1) of the values in the specified interval.\n* `stddev_over_time(range-vector)`: the population standard deviation of the values in the specified interval.\n* `stdvar_over_time(range-vector)`: the population standard variance of the values in the specified interval.\n\nNote that all values in the specified interval have the same weight in the\naggregation even if the values are not equally spaced throughout the interval.\n\n\n__PromQL Type:__ instant vector\n\n"
  },
  "range": {
    "start": {
      "line": 0,
      "character": 0
    },
    "end": {
      "line": 0,
      "character": 26
    }
  }
}
```

All line escape shouldn't be there. It would be wiser to have a proper json struct instead. And then the front-end can display it freely

**Comment by slrtbtfs** [comment]
Returning markdown is allowed and encouraged by the LSP specification. https://microsoft.github.io/language-server-protocol/specifications/specification-current/#markupContent

Furthermore, most language servers I dealt with so far do the same thing, so I don't see an issue here.

**Comment by slrtbtfs** [comment]
You can't just invent your own json struct here, since the response has to follow the LSP spec.

While there might be the theoretical possibility of markdown injections, the worst they can cause is bad formatting, assuming the client performs sanitizing as specified.

**Comment by Nexucis** [comment]
The issue will come when integrating codeMirror with Prometheus using the the rest API

**Comment by Nexucis** [comment]
> You can't just invent your own json struct here, since the response has to follow the LSP spec.

I was more thinking of returning a JSON in the value instead of a markdown actually

**Comment by slrtbtfs** [comment]
> The issue will come when integrating codeMirror with Prometheus using the rest API

With that background this issue makes more sense.

> I was more thinking of returning a JSON in the value instead of a markdown actually

This seems like a non trivial change that would imply added complexity in multiple components of the language server.

I'm sure there is a library that could solve this problem on the client side.

---

We also might want to revisit the discussion whether to use Codemirror or Monaco in Prometheus.

[PromLens](https://promlens.com/), which has been written by @juliusv, uses Monaco and doesn't appear to have issues with long loading times caused by Monaco's size.

**Comment by Nexucis** [comment]
> This seems like a non trivial change that would imply added complexity in multiple components of the language server.
Well from my point on view it wasn't so hard. It is just matter of manually marshalling the json struct in order to have a string. But maybe it's not so trivial indeed.

**Comment by Nexucis** [comment]
Specially since the LSP struct are manually imported, we can freely override the JSON Marshal method in order to have something smooth

**Comment by slrtbtfs** [comment]
Without elaborating to much, let me assure you that changing the return types in such a way is way to complex for what we want to achieve.

> Specially since the LSP struct are manually imported, we can freely override the JSON Marshal method in order to have something smooth

While this is only one of the many problems, that would need to be solved here, the LSP structs are actually automatically transpiled from Typescript to Go, then included into gopls and then eventually vendored into this repo.

I have very little interest in messing with this process.

**Comment by juliusv** [comment]
> PromLens, which has been written by @juliusv, uses Monaco and doesn't appear to have issues with long loading times caused by Monaco's size.

Monaco is a bit (or a lot) of a pain to integrate cleanly into React apps, and is still pretty huge to include into Prometheus itself. Even for PromLens I'm currently looking at replacing it with CodeMirror Next (https://codemirror.net/6/), and collaborating with @Nexucis on some of that stuff (since the plan is to share features with Prometheus / OSS).

I have no opinion on the Markdown stuff, haven't looked at that yet. But yeah, can't we just parse the Markdown on the client?

**Comment by slrtbtfs** [comment]
Seems like the solution to handle this is parsing Markdown on the client side.

If you disagree, feel free to reopen.
