### ISSUE TITLE
Unsuccessful cast when setting configuration from VS Code

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus-community/promql-langserver#193]
This cast

https://github.com/prometheus-community/promql-langserver/blob/356efaf3f31e909b86fb593011524df8ad5c1363/langserver/config.go#L45

always fails, which makes it impossible to set configuration from VS Code.

To actually work, there first would need to be a cast to `map[string]interface{}` and then a second cast for the `promql` field.

**Comment by Nexucis** [comment]
can you try to display the error?

**Comment by slrtbtfs** [comment]
This requires a slightly patched version of the VS Code extension, which reflects the recent changes in the YAML config.

The error produced is this one:

https://github.com/prometheus-community/promql-langserver/blob/356efaf3f31e909b86fb593011524df8ad5c1363/langserver/config.go#L48-L51

**Comment by Nexucis** [comment]
ah ok I was more expected an unmarshal error :/, I missed a bit it was a cast issue. I will take a look at it then.
