### ISSUE TITLE
Export metrics to prometheus

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus-community/promql-langserver#58]

**Comment by slrtbtfs** [comment]
Especially for the REST API it would be nice to have some metrics.

**Comment by haibeey** [comment]
what are examples of metrics to be exported? 
i'am thinking "number of queries processed" as an example?

**Comment by squat** [comment]
The first step here is to instrument the rest API.
That means, we want to add basic wrappers around the handlers to track:
* request counts with codes and handler names (https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#InstrumentHandlerCounter); and
* request duration (https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#InstrumentHandlerDuration)

Exactly as done here: https://github.com/brancz/prometheus-example-app/blob/master/main.go

**Comment by haibeey** [comment]
okay . i would be taking this up if it's available?

**Comment by squat** [comment]
yes, certainly, that would be great :)
