### ISSUE TITLE
Use new metadata endpoint to retrieve data for hover and completion

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus-community/promql-langserver#76]
See https://github.com/prometheus/prometheus/issues/6395 .

**Comment by slrtbtfs** [comment]
This allows for more correct metadata on hover and more better metadata on completion.

**Comment by slrtbtfs** [comment]
It should be considered to add some compatibility check to avoid breakage with Prometheus Versions that do not support the new API.

**Comment by slrtbtfs** [comment]
It should be considered to add some compatibility check to avoid breakage with Prometheus Versions that do not support the new API.

**Comment by slrtbtfs** [comment]
Depends on https://github.com/prometheus/client_golang/issues/705 .

**Comment by drumilpatel2000** [comment]
@slrtbtfs Any plans. I would like to work on this as   

> Depends on [prometheus/client_golang#705](https://github.com/prometheus/client_golang/issues/705) .

is closed.

**Comment by slrtbtfs** [comment]
@drumilpatel2000 Currently no one is working on this, so a PR would be appreciated.

It might make sense to first do a PR where the response [here](https://github.com/prometheus-community/promql-langserver/blob/5cb2e49987617c7f3ef6abb7e86b92effb81e507/langserver/server.go#L154) is used to check the version of the connected Prometheus instance, since the new metadata endpoint is only supported since Prometheus version 2.15 .

**Comment by slrtbtfs** [comment]
The metadata can be used [here](https://github.com/prometheus-community/promql-langserver/blob/9eeabe35b95076ca4a141022ce58d11b0e7f1020/langserver/completion.go#L107) as well, so this issue is not yet closed.
